package Advent2021;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

@Tag("Unit")
public class DayTwoPartTwoTests
{
    @Test
    public void should_calculateWithAim()
    {
        final String inputString = "forward 5\n" +
                "down 5\n" +
                "forward 8\n" +
                "up 3\n" +
                "down 8\n" +
                "forward 2";
        final DayTwoPartTwo dayTwoPartTwo = new DayTwoPartTwo();
        final ArrayList<MoveOrder> moveOrders = dayTwoPartTwo.splitInputToMoveOrders(inputString);
        final int sumMovements = dayTwoPartTwo.sumMovements(moveOrders);
        assertThat(sumMovements).isEqualTo(900);

    }    @Test
    public void should_calculateWithAim_actual()
    {
        final String inputString = getActualInput();
        final DayTwoPartTwo dayTwoPartTwo = new DayTwoPartTwo();
        final ArrayList<MoveOrder> moveOrders = dayTwoPartTwo.splitInputToMoveOrders(inputString);
        final int sumMovements = dayTwoPartTwo.sumMovements(moveOrders);
        assertThat(sumMovements).isEqualTo(1698850445);

    }

    @Test
    public void should_addAimToDepth_whenMovingForward_to4()
    {
        final MoveOrder moveOrder = new MoveOrder("forward 2");
        int currentDepth = 0;
        int currentAim = 2;
        final int depthAfterMove = moveOrder.addDepthWithAim(currentDepth, currentAim);
        assertThat(depthAfterMove).isEqualTo(4);
    }

    @Test
    public void should_addAimToDepth_whenMovingForward_10()
    {
        final MoveOrder moveOrder = new MoveOrder("forward 2");
        int currentDepth = 6;
        int currentAim = 2;
        final int depthAfterMove = moveOrder.addDepthWithAim(currentDepth, currentAim);
        assertThat(depthAfterMove).isEqualTo(10);
    }
    @Test
    public void should_addAimToDepth_whenMovingForward_withAim0()
    {
        final MoveOrder moveOrder = new MoveOrder("forward 2");
        int currentDepth = 6;
        int currentAim = 0;
        final int depthAfterMove = moveOrder.addDepthWithAim(currentDepth, currentAim);
        assertThat(depthAfterMove).isEqualTo(6);
    }

    @Test
    public void shouldNot_addAimToDepth_whenNotMovingForward()
    {
        final MoveOrder moveOrder = new MoveOrder("down 2");
        int currentDepth = 6;
        int currentAim = 2;
        final int depthAfterMove = moveOrder.addDepthWithAim(currentDepth, currentAim);
        assertThat(depthAfterMove).isEqualTo(6);
    }
    @Test
    public void should_addAimToMovement_withNegativeAim()
    {
        final MoveOrder moveOrder = new MoveOrder("forward 2");
        int currentDepth = 6;
        int currentAim = -3;
        final int depthAfterMove = moveOrder.addDepthWithAim(currentDepth, currentAim);
        assertThat(depthAfterMove).isEqualTo(0);
    }

    @Test
    public void should_notAddAimToCurrentAim_whenMovingForward()
    {
        final MoveOrder moveOrder = new MoveOrder("forward 2");
        int currentAim = 0;
        final int updateAim = moveOrder.updateAim(currentAim);
        assertThat(updateAim).isEqualTo(0);
    }
    @Test
    public void should_AddAimToCurrentAim_whenMovingDown()
    {
        final MoveOrder moveOrder = new MoveOrder("down 2");
        int currentAim = 0;
        final int updateAim = moveOrder.updateAim(currentAim);
        assertThat(updateAim).isEqualTo(2);
    }
    @Test
    public void should_SubtractAimFromCurrentAim_whenMovingUp()
    {
        final MoveOrder moveOrder = new MoveOrder("up 2");
        int currentAim = 0;
        final int updateAim = moveOrder.updateAim(currentAim);
        assertThat(updateAim).isEqualTo(-2);
    }
    private String getActualInput()
    {
        return "forward 2\n" +
                "down 1\n" +
                "down 7\n" +
                "forward 6\n" +
                "down 6\n" +
                "down 6\n" +
                "forward 6\n" +
                "down 6\n" +
                "down 9\n" +
                "up 6\n" +
                "forward 5\n" +
                "down 1\n" +
                "down 7\n" +
                "forward 5\n" +
                "forward 8\n" +
                "forward 8\n" +
                "forward 3\n" +
                "down 3\n" +
                "down 9\n" +
                "down 1\n" +
                "forward 5\n" +
                "up 2\n" +
                "down 6\n" +
                "forward 9\n" +
                "up 5\n" +
                "forward 3\n" +
                "down 9\n" +
                "down 6\n" +
                "down 2\n" +
                "down 2\n" +
                "down 5\n" +
                "up 8\n" +
                "up 1\n" +
                "down 2\n" +
                "down 7\n" +
                "forward 1\n" +
                "down 1\n" +
                "down 4\n" +
                "down 2\n" +
                "forward 7\n" +
                "down 9\n" +
                "forward 3\n" +
                "up 1\n" +
                "up 6\n" +
                "forward 2\n" +
                "forward 2\n" +
                "down 5\n" +
                "down 5\n" +
                "forward 1\n" +
                "forward 5\n" +
                "down 6\n" +
                "forward 8\n" +
                "forward 5\n" +
                "up 8\n" +
                "down 7\n" +
                "forward 5\n" +
                "up 9\n" +
                "down 3\n" +
                "forward 7\n" +
                "up 8\n" +
                "down 3\n" +
                "down 3\n" +
                "up 8\n" +
                "down 1\n" +
                "down 5\n" +
                "up 8\n" +
                "down 5\n" +
                "forward 5\n" +
                "forward 4\n" +
                "up 8\n" +
                "forward 6\n" +
                "down 1\n" +
                "down 3\n" +
                "forward 8\n" +
                "forward 6\n" +
                "forward 2\n" +
                "down 9\n" +
                "up 9\n" +
                "forward 6\n" +
                "up 4\n" +
                "down 9\n" +
                "forward 3\n" +
                "forward 4\n" +
                "forward 4\n" +
                "up 2\n" +
                "forward 6\n" +
                "up 7\n" +
                "forward 4\n" +
                "down 7\n" +
                "forward 3\n" +
                "forward 1\n" +
                "forward 1\n" +
                "down 9\n" +
                "up 6\n" +
                "forward 9\n" +
                "down 1\n" +
                "up 4\n" +
                "forward 2\n" +
                "forward 1\n" +
                "down 3\n" +
                "down 2\n" +
                "forward 8\n" +
                "forward 4\n" +
                "forward 6\n" +
                "down 3\n" +
                "down 9\n" +
                "forward 7\n" +
                "forward 9\n" +
                "down 4\n" +
                "up 3\n" +
                "down 7\n" +
                "down 2\n" +
                "down 8\n" +
                "forward 7\n" +
                "down 5\n" +
                "forward 5\n" +
                "forward 9\n" +
                "down 7\n" +
                "down 4\n" +
                "down 2\n" +
                "up 6\n" +
                "forward 6\n" +
                "down 7\n" +
                "down 3\n" +
                "up 7\n" +
                "forward 4\n" +
                "down 7\n" +
                "forward 1\n" +
                "forward 1\n" +
                "up 1\n" +
                "up 8\n" +
                "down 7\n" +
                "forward 8\n" +
                "up 9\n" +
                "up 2\n" +
                "forward 8\n" +
                "forward 2\n" +
                "forward 3\n" +
                "forward 2\n" +
                "down 2\n" +
                "down 4\n" +
                "forward 1\n" +
                "forward 1\n" +
                "down 6\n" +
                "forward 5\n" +
                "down 9\n" +
                "down 9\n" +
                "down 3\n" +
                "forward 6\n" +
                "forward 5\n" +
                "down 4\n" +
                "forward 4\n" +
                "forward 6\n" +
                "down 9\n" +
                "down 4\n" +
                "forward 5\n" +
                "forward 6\n" +
                "forward 4\n" +
                "forward 6\n" +
                "forward 7\n" +
                "down 6\n" +
                "down 4\n" +
                "up 8\n" +
                "down 4\n" +
                "forward 9\n" +
                "down 3\n" +
                "down 8\n" +
                "down 5\n" +
                "up 6\n" +
                "forward 7\n" +
                "forward 8\n" +
                "forward 8\n" +
                "down 5\n" +
                "up 3\n" +
                "down 3\n" +
                "forward 4\n" +
                "forward 4\n" +
                "up 9\n" +
                "forward 6\n" +
                "down 1\n" +
                "down 1\n" +
                "down 7\n" +
                "down 6\n" +
                "forward 9\n" +
                "forward 2\n" +
                "down 5\n" +
                "up 4\n" +
                "down 5\n" +
                "forward 8\n" +
                "down 8\n" +
                "forward 1\n" +
                "forward 4\n" +
                "up 2\n" +
                "down 4\n" +
                "forward 1\n" +
                "down 6\n" +
                "forward 1\n" +
                "forward 3\n" +
                "up 8\n" +
                "forward 1\n" +
                "up 8\n" +
                "down 7\n" +
                "forward 6\n" +
                "up 5\n" +
                "down 6\n" +
                "up 8\n" +
                "down 7\n" +
                "down 6\n" +
                "forward 7\n" +
                "forward 9\n" +
                "forward 2\n" +
                "down 6\n" +
                "down 4\n" +
                "up 2\n" +
                "forward 1\n" +
                "down 8\n" +
                "forward 9\n" +
                "down 5\n" +
                "down 7\n" +
                "forward 6\n" +
                "up 1\n" +
                "forward 2\n" +
                "forward 3\n" +
                "forward 9\n" +
                "up 3\n" +
                "forward 7\n" +
                "up 7\n" +
                "up 7\n" +
                "down 5\n" +
                "up 7\n" +
                "down 8\n" +
                "forward 2\n" +
                "down 4\n" +
                "down 6\n" +
                "up 2\n" +
                "down 7\n" +
                "forward 4\n" +
                "down 2\n" +
                "forward 3\n" +
                "forward 7\n" +
                "forward 4\n" +
                "forward 1\n" +
                "up 6\n" +
                "forward 3\n" +
                "forward 6\n" +
                "forward 9\n" +
                "up 9\n" +
                "down 2\n" +
                "forward 1\n" +
                "forward 9\n" +
                "forward 5\n" +
                "forward 7\n" +
                "forward 8\n" +
                "down 1\n" +
                "down 9\n" +
                "up 4\n" +
                "forward 5\n" +
                "up 9\n" +
                "down 9\n" +
                "down 7\n" +
                "forward 1\n" +
                "forward 3\n" +
                "forward 8\n" +
                "forward 2\n" +
                "forward 7\n" +
                "forward 7\n" +
                "forward 5\n" +
                "down 8\n" +
                "down 5\n" +
                "up 9\n" +
                "forward 2\n" +
                "down 9\n" +
                "forward 4\n" +
                "up 9\n" +
                "up 6\n" +
                "up 2\n" +
                "up 7\n" +
                "down 2\n" +
                "forward 8\n" +
                "forward 9\n" +
                "down 3\n" +
                "down 6\n" +
                "down 9\n" +
                "forward 8\n" +
                "down 4\n" +
                "down 2\n" +
                "down 8\n" +
                "down 8\n" +
                "down 9\n" +
                "up 4\n" +
                "down 5\n" +
                "forward 4\n" +
                "forward 7\n" +
                "down 6\n" +
                "down 3\n" +
                "forward 9\n" +
                "up 1\n" +
                "forward 3\n" +
                "down 1\n" +
                "down 8\n" +
                "up 1\n" +
                "down 7\n" +
                "down 5\n" +
                "forward 2\n" +
                "forward 3\n" +
                "up 9\n" +
                "down 7\n" +
                "up 9\n" +
                "up 8\n" +
                "up 3\n" +
                "forward 7\n" +
                "down 4\n" +
                "forward 8\n" +
                "forward 9\n" +
                "down 8\n" +
                "forward 1\n" +
                "up 7\n" +
                "up 4\n" +
                "down 2\n" +
                "forward 6\n" +
                "up 4\n" +
                "forward 1\n" +
                "up 1\n" +
                "forward 1\n" +
                "forward 2\n" +
                "up 4\n" +
                "up 2\n" +
                "up 3\n" +
                "forward 3\n" +
                "forward 9\n" +
                "forward 2\n" +
                "down 1\n" +
                "forward 9\n" +
                "down 7\n" +
                "forward 3\n" +
                "down 3\n" +
                "up 1\n" +
                "down 2\n" +
                "forward 9\n" +
                "down 7\n" +
                "down 5\n" +
                "up 5\n" +
                "down 2\n" +
                "down 5\n" +
                "forward 6\n" +
                "forward 9\n" +
                "forward 3\n" +
                "down 5\n" +
                "down 9\n" +
                "forward 6\n" +
                "up 3\n" +
                "down 6\n" +
                "down 8\n" +
                "up 8\n" +
                "down 1\n" +
                "forward 2\n" +
                "down 1\n" +
                "up 5\n" +
                "down 8\n" +
                "up 4\n" +
                "down 2\n" +
                "forward 6\n" +
                "forward 1\n" +
                "down 8\n" +
                "down 4\n" +
                "down 2\n" +
                "forward 4\n" +
                "down 7\n" +
                "up 9\n" +
                "forward 6\n" +
                "forward 5\n" +
                "down 4\n" +
                "down 5\n" +
                "up 6\n" +
                "down 6\n" +
                "forward 4\n" +
                "forward 8\n" +
                "up 9\n" +
                "down 8\n" +
                "forward 3\n" +
                "down 4\n" +
                "down 9\n" +
                "up 8\n" +
                "down 1\n" +
                "forward 7\n" +
                "down 5\n" +
                "down 1\n" +
                "forward 7\n" +
                "up 4\n" +
                "forward 9\n" +
                "up 6\n" +
                "forward 8\n" +
                "forward 1\n" +
                "up 8\n" +
                "up 8\n" +
                "up 3\n" +
                "forward 2\n" +
                "forward 3\n" +
                "forward 6\n" +
                "forward 8\n" +
                "forward 4\n" +
                "down 7\n" +
                "up 8\n" +
                "forward 4\n" +
                "down 3\n" +
                "down 2\n" +
                "down 5\n" +
                "down 4\n" +
                "up 2\n" +
                "up 1\n" +
                "down 3\n" +
                "down 5\n" +
                "down 3\n" +
                "up 6\n" +
                "down 8\n" +
                "down 7\n" +
                "down 9\n" +
                "forward 2\n" +
                "down 4\n" +
                "up 1\n" +
                "forward 4\n" +
                "down 9\n" +
                "forward 8\n" +
                "up 3\n" +
                "down 4\n" +
                "down 1\n" +
                "up 3\n" +
                "forward 7\n" +
                "forward 9\n" +
                "down 5\n" +
                "up 7\n" +
                "forward 4\n" +
                "down 4\n" +
                "up 8\n" +
                "down 2\n" +
                "up 7\n" +
                "up 3\n" +
                "forward 7\n" +
                "down 7\n" +
                "down 4\n" +
                "forward 6\n" +
                "up 5\n" +
                "forward 8\n" +
                "down 4\n" +
                "down 9\n" +
                "forward 3\n" +
                "down 6\n" +
                "forward 3\n" +
                "down 8\n" +
                "down 5\n" +
                "up 6\n" +
                "down 8\n" +
                "down 9\n" +
                "down 4\n" +
                "down 9\n" +
                "forward 7\n" +
                "down 4\n" +
                "down 7\n" +
                "forward 1\n" +
                "down 8\n" +
                "forward 9\n" +
                "forward 1\n" +
                "down 5\n" +
                "down 3\n" +
                "up 5\n" +
                "forward 9\n" +
                "down 7\n" +
                "down 7\n" +
                "up 3\n" +
                "up 9\n" +
                "down 4\n" +
                "down 5\n" +
                "forward 5\n" +
                "down 5\n" +
                "up 3\n" +
                "forward 8\n" +
                "down 5\n" +
                "forward 1\n" +
                "down 1\n" +
                "up 6\n" +
                "forward 1\n" +
                "forward 4\n" +
                "up 9\n" +
                "up 5\n" +
                "down 6\n" +
                "down 7\n" +
                "forward 8\n" +
                "down 4\n" +
                "forward 9\n" +
                "forward 6\n" +
                "down 7\n" +
                "down 2\n" +
                "up 1\n" +
                "down 4\n" +
                "down 5\n" +
                "up 7\n" +
                "down 7\n" +
                "down 3\n" +
                "up 8\n" +
                "forward 8\n" +
                "down 8\n" +
                "forward 5\n" +
                "down 6\n" +
                "down 7\n" +
                "forward 4\n" +
                "up 7\n" +
                "forward 9\n" +
                "down 7\n" +
                "up 7\n" +
                "forward 2\n" +
                "down 3\n" +
                "down 7\n" +
                "up 6\n" +
                "forward 2\n" +
                "down 1\n" +
                "forward 1\n" +
                "up 9\n" +
                "forward 6\n" +
                "forward 2\n" +
                "forward 5\n" +
                "up 1\n" +
                "forward 3\n" +
                "down 2\n" +
                "up 2\n" +
                "forward 4\n" +
                "up 2\n" +
                "down 2\n" +
                "down 9\n" +
                "up 9\n" +
                "forward 2\n" +
                "down 3\n" +
                "down 2\n" +
                "forward 9\n" +
                "forward 9\n" +
                "down 3\n" +
                "down 6\n" +
                "forward 3\n" +
                "down 7\n" +
                "up 6\n" +
                "down 8\n" +
                "forward 4\n" +
                "forward 8\n" +
                "forward 1\n" +
                "down 7\n" +
                "down 2\n" +
                "forward 6\n" +
                "forward 9\n" +
                "up 6\n" +
                "up 8\n" +
                "down 4\n" +
                "forward 9\n" +
                "forward 9\n" +
                "forward 1\n" +
                "forward 4\n" +
                "forward 3\n" +
                "up 9\n" +
                "down 8\n" +
                "down 7\n" +
                "down 4\n" +
                "down 1\n" +
                "down 9\n" +
                "down 7\n" +
                "forward 2\n" +
                "forward 7\n" +
                "forward 6\n" +
                "down 7\n" +
                "forward 2\n" +
                "forward 1\n" +
                "forward 8\n" +
                "forward 9\n" +
                "forward 2\n" +
                "down 5\n" +
                "down 9\n" +
                "up 7\n" +
                "forward 4\n" +
                "up 4\n" +
                "up 2\n" +
                "down 1\n" +
                "down 3\n" +
                "down 4\n" +
                "forward 1\n" +
                "up 4\n" +
                "up 1\n" +
                "up 4\n" +
                "down 6\n" +
                "down 7\n" +
                "forward 7\n" +
                "down 4\n" +
                "down 6\n" +
                "forward 4\n" +
                "forward 8\n" +
                "down 2\n" +
                "down 8\n" +
                "down 1\n" +
                "forward 1\n" +
                "down 7\n" +
                "down 1\n" +
                "down 6\n" +
                "up 2\n" +
                "down 9\n" +
                "forward 3\n" +
                "down 7\n" +
                "down 8\n" +
                "down 9\n" +
                "down 4\n" +
                "down 7\n" +
                "down 4\n" +
                "up 1\n" +
                "forward 1\n" +
                "forward 2\n" +
                "up 6\n" +
                "up 6\n" +
                "up 5\n" +
                "forward 4\n" +
                "down 3\n" +
                "down 9\n" +
                "forward 3\n" +
                "up 5\n" +
                "down 1\n" +
                "forward 7\n" +
                "down 6\n" +
                "down 2\n" +
                "up 3\n" +
                "up 8\n" +
                "up 5\n" +
                "forward 4\n" +
                "down 5\n" +
                "forward 5\n" +
                "forward 2\n" +
                "down 3\n" +
                "forward 3\n" +
                "forward 9\n" +
                "down 9\n" +
                "down 9\n" +
                "down 9\n" +
                "forward 8\n" +
                "forward 5\n" +
                "up 1\n" +
                "down 5\n" +
                "forward 3\n" +
                "forward 4\n" +
                "forward 2\n" +
                "up 1\n" +
                "up 2\n" +
                "up 8\n" +
                "down 6\n" +
                "up 4\n" +
                "forward 3\n" +
                "down 1\n" +
                "down 6\n" +
                "down 6\n" +
                "up 7\n" +
                "forward 7\n" +
                "down 8\n" +
                "up 2\n" +
                "up 1\n" +
                "up 5\n" +
                "forward 4\n" +
                "down 4\n" +
                "down 8\n" +
                "down 2\n" +
                "down 5\n" +
                "down 4\n" +
                "up 4\n" +
                "up 7\n" +
                "forward 2\n" +
                "forward 4\n" +
                "forward 2\n" +
                "down 6\n" +
                "down 9\n" +
                "up 3\n" +
                "up 6\n" +
                "forward 8\n" +
                "forward 6\n" +
                "forward 8\n" +
                "forward 9\n" +
                "down 7\n" +
                "forward 9\n" +
                "up 4\n" +
                "up 5\n" +
                "down 4\n" +
                "down 7\n" +
                "down 4\n" +
                "up 8\n" +
                "down 3\n" +
                "forward 8\n" +
                "down 2\n" +
                "down 4\n" +
                "forward 2\n" +
                "up 6\n" +
                "up 6\n" +
                "down 9\n" +
                "forward 6\n" +
                "forward 8\n" +
                "down 5\n" +
                "forward 5\n" +
                "down 3\n" +
                "down 6\n" +
                "up 9\n" +
                "forward 2\n" +
                "forward 8\n" +
                "up 4\n" +
                "forward 4\n" +
                "forward 2\n" +
                "down 4\n" +
                "forward 3\n" +
                "down 1\n" +
                "up 4\n" +
                "down 4\n" +
                "up 7\n" +
                "forward 2\n" +
                "forward 8\n" +
                "down 8\n" +
                "up 7\n" +
                "up 2\n" +
                "down 7\n" +
                "down 7\n" +
                "forward 8\n" +
                "forward 7\n" +
                "forward 9\n" +
                "down 4\n" +
                "down 5\n" +
                "down 9\n" +
                "down 5\n" +
                "forward 1\n" +
                "down 5\n" +
                "up 2\n" +
                "forward 6\n" +
                "forward 9\n" +
                "down 3\n" +
                "forward 5\n" +
                "down 1\n" +
                "forward 9\n" +
                "up 2\n" +
                "forward 1\n" +
                "up 9\n" +
                "forward 2\n" +
                "up 2\n" +
                "forward 4\n" +
                "forward 3\n" +
                "up 9\n" +
                "forward 4\n" +
                "forward 2\n" +
                "up 7\n" +
                "up 6\n" +
                "down 3\n" +
                "forward 7\n" +
                "forward 1\n" +
                "forward 6\n" +
                "down 2\n" +
                "down 8\n" +
                "forward 5\n" +
                "down 5\n" +
                "up 5\n" +
                "forward 5\n" +
                "down 6\n" +
                "forward 8\n" +
                "forward 4\n" +
                "down 2\n" +
                "up 8\n" +
                "forward 6\n" +
                "down 2\n" +
                "down 7\n" +
                "forward 5\n" +
                "down 4\n" +
                "down 5\n" +
                "up 6\n" +
                "down 3\n" +
                "up 6\n" +
                "down 8\n" +
                "forward 4\n" +
                "down 8\n" +
                "down 6\n" +
                "forward 2\n" +
                "forward 8\n" +
                "up 8\n" +
                "up 1\n" +
                "forward 6\n" +
                "down 2\n" +
                "down 6\n" +
                "forward 2\n" +
                "forward 2\n" +
                "down 8\n" +
                "forward 7\n" +
                "up 1\n" +
                "forward 1\n" +
                "down 8\n" +
                "forward 3\n" +
                "down 6\n" +
                "forward 7\n" +
                "forward 7\n" +
                "up 7\n" +
                "down 1\n" +
                "forward 8\n" +
                "up 7\n" +
                "forward 8\n" +
                "forward 8\n" +
                "forward 2\n" +
                "down 5\n" +
                "up 7\n" +
                "forward 1\n" +
                "forward 9\n" +
                "down 9\n" +
                "forward 8\n" +
                "down 6\n" +
                "down 7\n" +
                "up 4\n" +
                "down 5\n" +
                "forward 6\n" +
                "down 8\n" +
                "forward 5\n" +
                "up 6\n" +
                "up 4\n" +
                "forward 8\n" +
                "forward 5\n" +
                "forward 1\n" +
                "forward 3\n" +
                "up 2\n" +
                "down 3\n" +
                "down 4\n" +
                "down 2\n" +
                "forward 3\n" +
                "forward 2\n" +
                "up 8\n" +
                "up 1\n" +
                "forward 5\n" +
                "up 8\n" +
                "down 1\n" +
                "up 4\n" +
                "down 6\n" +
                "forward 1\n" +
                "down 3\n" +
                "up 8\n" +
                "down 3\n" +
                "forward 5\n" +
                "down 7\n" +
                "forward 3\n" +
                "down 1\n" +
                "up 8\n" +
                "up 6\n" +
                "down 4\n" +
                "down 8\n" +
                "up 2\n" +
                "forward 1\n" +
                "forward 8\n" +
                "down 4\n" +
                "down 8\n" +
                "down 4\n" +
                "up 7\n" +
                "down 4\n" +
                "forward 7\n" +
                "forward 4\n" +
                "forward 2\n" +
                "forward 6\n" +
                "up 4\n" +
                "down 5\n" +
                "forward 8\n" +
                "forward 9\n" +
                "down 1\n" +
                "down 2\n" +
                "down 2\n" +
                "forward 6\n" +
                "forward 1\n" +
                "forward 4\n" +
                "down 7\n" +
                "forward 6\n" +
                "forward 9\n" +
                "down 5\n" +
                "forward 9\n" +
                "up 4\n" +
                "down 2\n" +
                "down 6\n" +
                "forward 5\n" +
                "forward 3\n" +
                "forward 1\n" +
                "forward 6\n" +
                "forward 5\n" +
                "forward 2\n" +
                "down 9\n" +
                "forward 1\n" +
                "up 5\n" +
                "down 2\n" +
                "down 8\n" +
                "up 5\n" +
                "down 3\n" +
                "up 1\n" +
                "forward 5\n" +
                "forward 8\n" +
                "forward 2\n" +
                "down 3\n" +
                "down 7\n" +
                "up 3\n" +
                "up 8\n" +
                "forward 5\n" +
                "up 8\n" +
                "forward 4\n" +
                "down 7\n" +
                "forward 4\n" +
                "down 1\n" +
                "forward 2\n" +
                "forward 8\n" +
                "up 9\n" +
                "up 1\n" +
                "forward 3\n" +
                "down 6\n" +
                "up 5\n" +
                "down 9\n" +
                "forward 8\n" +
                "forward 3\n" +
                "down 7\n" +
                "forward 3\n" +
                "up 9\n" +
                "down 2\n" +
                "forward 2\n" +
                "down 6\n" +
                "down 9\n" +
                "down 4\n" +
                "down 4\n" +
                "down 7\n" +
                "up 6\n" +
                "up 2\n" +
                "down 7\n" +
                "forward 5\n" +
                "up 1\n" +
                "down 6\n" +
                "up 2\n" +
                "forward 8\n" +
                "up 6\n" +
                "forward 4\n" +
                "down 2\n" +
                "up 5\n" +
                "down 6\n" +
                "down 5\n" +
                "forward 8\n" +
                "forward 4\n" +
                "down 5\n" +
                "forward 5\n" +
                "forward 3\n" +
                "down 2\n" +
                "forward 3\n" +
                "up 3\n" +
                "down 4\n" +
                "up 2\n" +
                "forward 9\n" +
                "up 8\n" +
                "forward 9\n" +
                "up 5\n" +
                "up 1\n" +
                "forward 9\n" +
                "down 8\n" +
                "down 3\n" +
                "forward 9\n" +
                "up 4\n" +
                "down 1\n" +
                "forward 8\n" +
                "down 6\n" +
                "down 1\n" +
                "down 2\n" +
                "down 9\n" +
                "down 1\n" +
                "forward 5\n" +
                "down 7\n" +
                "forward 1\n" +
                "up 6\n" +
                "down 1\n" +
                "down 6\n" +
                "forward 6\n" +
                "forward 9\n" +
                "down 6\n" +
                "forward 1\n" +
                "forward 4\n" +
                "up 4\n" +
                "forward 1\n" +
                "up 9\n" +
                "forward 3\n" +
                "forward 8\n" +
                "down 3\n" +
                "down 7\n" +
                "forward 4\n" +
                "up 1\n" +
                "down 1\n" +
                "forward 1\n" +
                "down 3\n" +
                "down 6\n" +
                "down 9\n" +
                "down 6\n" +
                "forward 4\n" +
                "down 1\n" +
                "up 4\n" +
                "forward 8\n" +
                "down 6\n" +
                "up 6\n" +
                "down 5\n" +
                "up 8\n" +
                "forward 4\n" +
                "up 7\n" +
                "forward 4\n" +
                "forward 2\n" +
                "down 7\n" +
                "forward 2";
    }
}
