package Advent2021.DayTwo;

import Advent2021.DayTwo.DayTwoPartOne;
import Advent2021.DayTwo.MoveOrder;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

@Tag("Unit")
public class DayTwoPartOneTests
{
    @Test
    public void should_returnHorizontalMovement_fromMoveOrder()
    {
        final MoveOrder moveOrder = new MoveOrder("forward 5");
        assertThat(moveOrder.addHorizontal(0)).isEqualTo(5);
        assertThat(moveOrder.addVertical(0)).isEqualTo(0);
    }

    @Test
    public void should_returnVerticalMovement_down_fromMoveOrder()
    {
        final MoveOrder moveOrder = new MoveOrder("down 2");
        assertThat(moveOrder.addHorizontal(3)).isEqualTo(3);
        assertThat(moveOrder.addVertical(0)).isEqualTo(2);
    }

    @Test
    public void should_returnVerticalMovement_up_fromMoveOrder()
    {
        final MoveOrder moveOrder = new MoveOrder("up 6");
        assertThat(moveOrder.addHorizontal(7)).isEqualTo(7);
        assertThat(moveOrder.addVertical(24)).isEqualTo(18);
    }

    @Test
    public void should_splitInputAndCreateMoveOrders()
    {
        final String inputString = "forward 5\n" +
                "down 5\n" +
                "forward 8\n" +
                "up 3\n" +
                "down 8\n" +
                "forward 2";
        final DayTwoPartOne dayTwoPartOne = new DayTwoPartOne();
        final ArrayList<MoveOrder> moveOrders = dayTwoPartOne.splitInputToMoveOrders(inputString);
        assertThat(moveOrders.size()).isEqualTo(6);
    }

    @Test
    public void should_sumMovements_to150()
    {
        final MoveOrder forward5 = new MoveOrder("forward 5");
        final MoveOrder down5 = new MoveOrder("down 5");
        final MoveOrder forward8 = new MoveOrder("forward 8");
        final MoveOrder up3 = new MoveOrder("up 3");
        final MoveOrder forward2 = new MoveOrder("forward 2");
        final MoveOrder down8 = new MoveOrder("down 8");
        final List<MoveOrder> moveOrders = List.of(forward5, down5, forward8, up3, forward2, down8);
        final DayTwoPartOne dayTwoPartOne = new DayTwoPartOne();
        final int sumMovements = dayTwoPartOne.sumMovements(moveOrders);
        assertThat(sumMovements).isEqualTo(150);
    }

    @Test
    public void should_sumMovements_to54()
    {
        final MoveOrder forward5 = new MoveOrder("forward 3");
        final MoveOrder down5 = new MoveOrder("down 8");
        final MoveOrder forward8 = new MoveOrder("forward 1");
        final MoveOrder up3 = new MoveOrder("up 3");
        final MoveOrder forward2 = new MoveOrder("forward 2");
        final MoveOrder down8 = new MoveOrder("down 4");
        final List<MoveOrder> moveOrders = List.of(forward5, down5, forward8, up3, forward2, down8);
        final DayTwoPartOne dayTwoPartOne = new DayTwoPartOne();
        final int sumMovements = dayTwoPartOne.sumMovements(moveOrders);
        assertThat(sumMovements).isEqualTo(54);
    }

    @Test
    public void should_processTheEntireInput()
    {
        final String inputString = "forward 5\n" +
                "down 5\n" +
                "forward 8\n" +
                "up 3\n" +
                "down 8\n" +
                "forward 2";
        final DayTwoPartOne dayTwoPartOne = new DayTwoPartOne();
        final int totalValue = dayTwoPartOne.processInput(inputString);
        assertThat(totalValue).isEqualTo(150);
    }
    @Test
    public void should_process_andGetRealValue()
    {
        final String inputString = getActualInput();
        final DayTwoPartOne dayTwoPartOne = new DayTwoPartOne();
        final int totalValue = dayTwoPartOne.processInput(inputString);
        assertThat(totalValue).isEqualTo(1694130    );
    }

    private String getActualInput()
    {
        return "forward 2\n" +
                "down 1\n" +
                "down 7\n" +
                "forward 6\n" +
                "down 6\n" +
                "down 6\n" +
                "forward 6\n" +
                "down 6\n" +
                "down 9\n" +
                "up 6\n" +
                "forward 5\n" +
                "down 1\n" +
                "down 7\n" +
                "forward 5\n" +
                "forward 8\n" +
                "forward 8\n" +
                "forward 3\n" +
                "down 3\n" +
                "down 9\n" +
                "down 1\n" +
                "forward 5\n" +
                "up 2\n" +
                "down 6\n" +
                "forward 9\n" +
                "up 5\n" +
                "forward 3\n" +
                "down 9\n" +
                "down 6\n" +
                "down 2\n" +
                "down 2\n" +
                "down 5\n" +
                "up 8\n" +
                "up 1\n" +
                "down 2\n" +
                "down 7\n" +
                "forward 1\n" +
                "down 1\n" +
                "down 4\n" +
                "down 2\n" +
                "forward 7\n" +
                "down 9\n" +
                "forward 3\n" +
                "up 1\n" +
                "up 6\n" +
                "forward 2\n" +
                "forward 2\n" +
                "down 5\n" +
                "down 5\n" +
                "forward 1\n" +
                "forward 5\n" +
                "down 6\n" +
                "forward 8\n" +
                "forward 5\n" +
                "up 8\n" +
                "down 7\n" +
                "forward 5\n" +
                "up 9\n" +
                "down 3\n" +
                "forward 7\n" +
                "up 8\n" +
                "down 3\n" +
                "down 3\n" +
                "up 8\n" +
                "down 1\n" +
                "down 5\n" +
                "up 8\n" +
                "down 5\n" +
                "forward 5\n" +
                "forward 4\n" +
                "up 8\n" +
                "forward 6\n" +
                "down 1\n" +
                "down 3\n" +
                "forward 8\n" +
                "forward 6\n" +
                "forward 2\n" +
                "down 9\n" +
                "up 9\n" +
                "forward 6\n" +
                "up 4\n" +
                "down 9\n" +
                "forward 3\n" +
                "forward 4\n" +
                "forward 4\n" +
                "up 2\n" +
                "forward 6\n" +
                "up 7\n" +
                "forward 4\n" +
                "down 7\n" +
                "forward 3\n" +
                "forward 1\n" +
                "forward 1\n" +
                "down 9\n" +
                "up 6\n" +
                "forward 9\n" +
                "down 1\n" +
                "up 4\n" +
                "forward 2\n" +
                "forward 1\n" +
                "down 3\n" +
                "down 2\n" +
                "forward 8\n" +
                "forward 4\n" +
                "forward 6\n" +
                "down 3\n" +
                "down 9\n" +
                "forward 7\n" +
                "forward 9\n" +
                "down 4\n" +
                "up 3\n" +
                "down 7\n" +
                "down 2\n" +
                "down 8\n" +
                "forward 7\n" +
                "down 5\n" +
                "forward 5\n" +
                "forward 9\n" +
                "down 7\n" +
                "down 4\n" +
                "down 2\n" +
                "up 6\n" +
                "forward 6\n" +
                "down 7\n" +
                "down 3\n" +
                "up 7\n" +
                "forward 4\n" +
                "down 7\n" +
                "forward 1\n" +
                "forward 1\n" +
                "up 1\n" +
                "up 8\n" +
                "down 7\n" +
                "forward 8\n" +
                "up 9\n" +
                "up 2\n" +
                "forward 8\n" +
                "forward 2\n" +
                "forward 3\n" +
                "forward 2\n" +
                "down 2\n" +
                "down 4\n" +
                "forward 1\n" +
                "forward 1\n" +
                "down 6\n" +
                "forward 5\n" +
                "down 9\n" +
                "down 9\n" +
                "down 3\n" +
                "forward 6\n" +
                "forward 5\n" +
                "down 4\n" +
                "forward 4\n" +
                "forward 6\n" +
                "down 9\n" +
                "down 4\n" +
                "forward 5\n" +
                "forward 6\n" +
                "forward 4\n" +
                "forward 6\n" +
                "forward 7\n" +
                "down 6\n" +
                "down 4\n" +
                "up 8\n" +
                "down 4\n" +
                "forward 9\n" +
                "down 3\n" +
                "down 8\n" +
                "down 5\n" +
                "up 6\n" +
                "forward 7\n" +
                "forward 8\n" +
                "forward 8\n" +
                "down 5\n" +
                "up 3\n" +
                "down 3\n" +
                "forward 4\n" +
                "forward 4\n" +
                "up 9\n" +
                "forward 6\n" +
                "down 1\n" +
                "down 1\n" +
                "down 7\n" +
                "down 6\n" +
                "forward 9\n" +
                "forward 2\n" +
                "down 5\n" +
                "up 4\n" +
                "down 5\n" +
                "forward 8\n" +
                "down 8\n" +
                "forward 1\n" +
                "forward 4\n" +
                "up 2\n" +
                "down 4\n" +
                "forward 1\n" +
                "down 6\n" +
                "forward 1\n" +
                "forward 3\n" +
                "up 8\n" +
                "forward 1\n" +
                "up 8\n" +
                "down 7\n" +
                "forward 6\n" +
                "up 5\n" +
                "down 6\n" +
                "up 8\n" +
                "down 7\n" +
                "down 6\n" +
                "forward 7\n" +
                "forward 9\n" +
                "forward 2\n" +
                "down 6\n" +
                "down 4\n" +
                "up 2\n" +
                "forward 1\n" +
                "down 8\n" +
                "forward 9\n" +
                "down 5\n" +
                "down 7\n" +
                "forward 6\n" +
                "up 1\n" +
                "forward 2\n" +
                "forward 3\n" +
                "forward 9\n" +
                "up 3\n" +
                "forward 7\n" +
                "up 7\n" +
                "up 7\n" +
                "down 5\n" +
                "up 7\n" +
                "down 8\n" +
                "forward 2\n" +
                "down 4\n" +
                "down 6\n" +
                "up 2\n" +
                "down 7\n" +
                "forward 4\n" +
                "down 2\n" +
                "forward 3\n" +
                "forward 7\n" +
                "forward 4\n" +
                "forward 1\n" +
                "up 6\n" +
                "forward 3\n" +
                "forward 6\n" +
                "forward 9\n" +
                "up 9\n" +
                "down 2\n" +
                "forward 1\n" +
                "forward 9\n" +
                "forward 5\n" +
                "forward 7\n" +
                "forward 8\n" +
                "down 1\n" +
                "down 9\n" +
                "up 4\n" +
                "forward 5\n" +
                "up 9\n" +
                "down 9\n" +
                "down 7\n" +
                "forward 1\n" +
                "forward 3\n" +
                "forward 8\n" +
                "forward 2\n" +
                "forward 7\n" +
                "forward 7\n" +
                "forward 5\n" +
                "down 8\n" +
                "down 5\n" +
                "up 9\n" +
                "forward 2\n" +
                "down 9\n" +
                "forward 4\n" +
                "up 9\n" +
                "up 6\n" +
                "up 2\n" +
                "up 7\n" +
                "down 2\n" +
                "forward 8\n" +
                "forward 9\n" +
                "down 3\n" +
                "down 6\n" +
                "down 9\n" +
                "forward 8\n" +
                "down 4\n" +
                "down 2\n" +
                "down 8\n" +
                "down 8\n" +
                "down 9\n" +
                "up 4\n" +
                "down 5\n" +
                "forward 4\n" +
                "forward 7\n" +
                "down 6\n" +
                "down 3\n" +
                "forward 9\n" +
                "up 1\n" +
                "forward 3\n" +
                "down 1\n" +
                "down 8\n" +
                "up 1\n" +
                "down 7\n" +
                "down 5\n" +
                "forward 2\n" +
                "forward 3\n" +
                "up 9\n" +
                "down 7\n" +
                "up 9\n" +
                "up 8\n" +
                "up 3\n" +
                "forward 7\n" +
                "down 4\n" +
                "forward 8\n" +
                "forward 9\n" +
                "down 8\n" +
                "forward 1\n" +
                "up 7\n" +
                "up 4\n" +
                "down 2\n" +
                "forward 6\n" +
                "up 4\n" +
                "forward 1\n" +
                "up 1\n" +
                "forward 1\n" +
                "forward 2\n" +
                "up 4\n" +
                "up 2\n" +
                "up 3\n" +
                "forward 3\n" +
                "forward 9\n" +
                "forward 2\n" +
                "down 1\n" +
                "forward 9\n" +
                "down 7\n" +
                "forward 3\n" +
                "down 3\n" +
                "up 1\n" +
                "down 2\n" +
                "forward 9\n" +
                "down 7\n" +
                "down 5\n" +
                "up 5\n" +
                "down 2\n" +
                "down 5\n" +
                "forward 6\n" +
                "forward 9\n" +
                "forward 3\n" +
                "down 5\n" +
                "down 9\n" +
                "forward 6\n" +
                "up 3\n" +
                "down 6\n" +
                "down 8\n" +
                "up 8\n" +
                "down 1\n" +
                "forward 2\n" +
                "down 1\n" +
                "up 5\n" +
                "down 8\n" +
                "up 4\n" +
                "down 2\n" +
                "forward 6\n" +
                "forward 1\n" +
                "down 8\n" +
                "down 4\n" +
                "down 2\n" +
                "forward 4\n" +
                "down 7\n" +
                "up 9\n" +
                "forward 6\n" +
                "forward 5\n" +
                "down 4\n" +
                "down 5\n" +
                "up 6\n" +
                "down 6\n" +
                "forward 4\n" +
                "forward 8\n" +
                "up 9\n" +
                "down 8\n" +
                "forward 3\n" +
                "down 4\n" +
                "down 9\n" +
                "up 8\n" +
                "down 1\n" +
                "forward 7\n" +
                "down 5\n" +
                "down 1\n" +
                "forward 7\n" +
                "up 4\n" +
                "forward 9\n" +
                "up 6\n" +
                "forward 8\n" +
                "forward 1\n" +
                "up 8\n" +
                "up 8\n" +
                "up 3\n" +
                "forward 2\n" +
                "forward 3\n" +
                "forward 6\n" +
                "forward 8\n" +
                "forward 4\n" +
                "down 7\n" +
                "up 8\n" +
                "forward 4\n" +
                "down 3\n" +
                "down 2\n" +
                "down 5\n" +
                "down 4\n" +
                "up 2\n" +
                "up 1\n" +
                "down 3\n" +
                "down 5\n" +
                "down 3\n" +
                "up 6\n" +
                "down 8\n" +
                "down 7\n" +
                "down 9\n" +
                "forward 2\n" +
                "down 4\n" +
                "up 1\n" +
                "forward 4\n" +
                "down 9\n" +
                "forward 8\n" +
                "up 3\n" +
                "down 4\n" +
                "down 1\n" +
                "up 3\n" +
                "forward 7\n" +
                "forward 9\n" +
                "down 5\n" +
                "up 7\n" +
                "forward 4\n" +
                "down 4\n" +
                "up 8\n" +
                "down 2\n" +
                "up 7\n" +
                "up 3\n" +
                "forward 7\n" +
                "down 7\n" +
                "down 4\n" +
                "forward 6\n" +
                "up 5\n" +
                "forward 8\n" +
                "down 4\n" +
                "down 9\n" +
                "forward 3\n" +
                "down 6\n" +
                "forward 3\n" +
                "down 8\n" +
                "down 5\n" +
                "up 6\n" +
                "down 8\n" +
                "down 9\n" +
                "down 4\n" +
                "down 9\n" +
                "forward 7\n" +
                "down 4\n" +
                "down 7\n" +
                "forward 1\n" +
                "down 8\n" +
                "forward 9\n" +
                "forward 1\n" +
                "down 5\n" +
                "down 3\n" +
                "up 5\n" +
                "forward 9\n" +
                "down 7\n" +
                "down 7\n" +
                "up 3\n" +
                "up 9\n" +
                "down 4\n" +
                "down 5\n" +
                "forward 5\n" +
                "down 5\n" +
                "up 3\n" +
                "forward 8\n" +
                "down 5\n" +
                "forward 1\n" +
                "down 1\n" +
                "up 6\n" +
                "forward 1\n" +
                "forward 4\n" +
                "up 9\n" +
                "up 5\n" +
                "down 6\n" +
                "down 7\n" +
                "forward 8\n" +
                "down 4\n" +
                "forward 9\n" +
                "forward 6\n" +
                "down 7\n" +
                "down 2\n" +
                "up 1\n" +
                "down 4\n" +
                "down 5\n" +
                "up 7\n" +
                "down 7\n" +
                "down 3\n" +
                "up 8\n" +
                "forward 8\n" +
                "down 8\n" +
                "forward 5\n" +
                "down 6\n" +
                "down 7\n" +
                "forward 4\n" +
                "up 7\n" +
                "forward 9\n" +
                "down 7\n" +
                "up 7\n" +
                "forward 2\n" +
                "down 3\n" +
                "down 7\n" +
                "up 6\n" +
                "forward 2\n" +
                "down 1\n" +
                "forward 1\n" +
                "up 9\n" +
                "forward 6\n" +
                "forward 2\n" +
                "forward 5\n" +
                "up 1\n" +
                "forward 3\n" +
                "down 2\n" +
                "up 2\n" +
                "forward 4\n" +
                "up 2\n" +
                "down 2\n" +
                "down 9\n" +
                "up 9\n" +
                "forward 2\n" +
                "down 3\n" +
                "down 2\n" +
                "forward 9\n" +
                "forward 9\n" +
                "down 3\n" +
                "down 6\n" +
                "forward 3\n" +
                "down 7\n" +
                "up 6\n" +
                "down 8\n" +
                "forward 4\n" +
                "forward 8\n" +
                "forward 1\n" +
                "down 7\n" +
                "down 2\n" +
                "forward 6\n" +
                "forward 9\n" +
                "up 6\n" +
                "up 8\n" +
                "down 4\n" +
                "forward 9\n" +
                "forward 9\n" +
                "forward 1\n" +
                "forward 4\n" +
                "forward 3\n" +
                "up 9\n" +
                "down 8\n" +
                "down 7\n" +
                "down 4\n" +
                "down 1\n" +
                "down 9\n" +
                "down 7\n" +
                "forward 2\n" +
                "forward 7\n" +
                "forward 6\n" +
                "down 7\n" +
                "forward 2\n" +
                "forward 1\n" +
                "forward 8\n" +
                "forward 9\n" +
                "forward 2\n" +
                "down 5\n" +
                "down 9\n" +
                "up 7\n" +
                "forward 4\n" +
                "up 4\n" +
                "up 2\n" +
                "down 1\n" +
                "down 3\n" +
                "down 4\n" +
                "forward 1\n" +
                "up 4\n" +
                "up 1\n" +
                "up 4\n" +
                "down 6\n" +
                "down 7\n" +
                "forward 7\n" +
                "down 4\n" +
                "down 6\n" +
                "forward 4\n" +
                "forward 8\n" +
                "down 2\n" +
                "down 8\n" +
                "down 1\n" +
                "forward 1\n" +
                "down 7\n" +
                "down 1\n" +
                "down 6\n" +
                "up 2\n" +
                "down 9\n" +
                "forward 3\n" +
                "down 7\n" +
                "down 8\n" +
                "down 9\n" +
                "down 4\n" +
                "down 7\n" +
                "down 4\n" +
                "up 1\n" +
                "forward 1\n" +
                "forward 2\n" +
                "up 6\n" +
                "up 6\n" +
                "up 5\n" +
                "forward 4\n" +
                "down 3\n" +
                "down 9\n" +
                "forward 3\n" +
                "up 5\n" +
                "down 1\n" +
                "forward 7\n" +
                "down 6\n" +
                "down 2\n" +
                "up 3\n" +
                "up 8\n" +
                "up 5\n" +
                "forward 4\n" +
                "down 5\n" +
                "forward 5\n" +
                "forward 2\n" +
                "down 3\n" +
                "forward 3\n" +
                "forward 9\n" +
                "down 9\n" +
                "down 9\n" +
                "down 9\n" +
                "forward 8\n" +
                "forward 5\n" +
                "up 1\n" +
                "down 5\n" +
                "forward 3\n" +
                "forward 4\n" +
                "forward 2\n" +
                "up 1\n" +
                "up 2\n" +
                "up 8\n" +
                "down 6\n" +
                "up 4\n" +
                "forward 3\n" +
                "down 1\n" +
                "down 6\n" +
                "down 6\n" +
                "up 7\n" +
                "forward 7\n" +
                "down 8\n" +
                "up 2\n" +
                "up 1\n" +
                "up 5\n" +
                "forward 4\n" +
                "down 4\n" +
                "down 8\n" +
                "down 2\n" +
                "down 5\n" +
                "down 4\n" +
                "up 4\n" +
                "up 7\n" +
                "forward 2\n" +
                "forward 4\n" +
                "forward 2\n" +
                "down 6\n" +
                "down 9\n" +
                "up 3\n" +
                "up 6\n" +
                "forward 8\n" +
                "forward 6\n" +
                "forward 8\n" +
                "forward 9\n" +
                "down 7\n" +
                "forward 9\n" +
                "up 4\n" +
                "up 5\n" +
                "down 4\n" +
                "down 7\n" +
                "down 4\n" +
                "up 8\n" +
                "down 3\n" +
                "forward 8\n" +
                "down 2\n" +
                "down 4\n" +
                "forward 2\n" +
                "up 6\n" +
                "up 6\n" +
                "down 9\n" +
                "forward 6\n" +
                "forward 8\n" +
                "down 5\n" +
                "forward 5\n" +
                "down 3\n" +
                "down 6\n" +
                "up 9\n" +
                "forward 2\n" +
                "forward 8\n" +
                "up 4\n" +
                "forward 4\n" +
                "forward 2\n" +
                "down 4\n" +
                "forward 3\n" +
                "down 1\n" +
                "up 4\n" +
                "down 4\n" +
                "up 7\n" +
                "forward 2\n" +
                "forward 8\n" +
                "down 8\n" +
                "up 7\n" +
                "up 2\n" +
                "down 7\n" +
                "down 7\n" +
                "forward 8\n" +
                "forward 7\n" +
                "forward 9\n" +
                "down 4\n" +
                "down 5\n" +
                "down 9\n" +
                "down 5\n" +
                "forward 1\n" +
                "down 5\n" +
                "up 2\n" +
                "forward 6\n" +
                "forward 9\n" +
                "down 3\n" +
                "forward 5\n" +
                "down 1\n" +
                "forward 9\n" +
                "up 2\n" +
                "forward 1\n" +
                "up 9\n" +
                "forward 2\n" +
                "up 2\n" +
                "forward 4\n" +
                "forward 3\n" +
                "up 9\n" +
                "forward 4\n" +
                "forward 2\n" +
                "up 7\n" +
                "up 6\n" +
                "down 3\n" +
                "forward 7\n" +
                "forward 1\n" +
                "forward 6\n" +
                "down 2\n" +
                "down 8\n" +
                "forward 5\n" +
                "down 5\n" +
                "up 5\n" +
                "forward 5\n" +
                "down 6\n" +
                "forward 8\n" +
                "forward 4\n" +
                "down 2\n" +
                "up 8\n" +
                "forward 6\n" +
                "down 2\n" +
                "down 7\n" +
                "forward 5\n" +
                "down 4\n" +
                "down 5\n" +
                "up 6\n" +
                "down 3\n" +
                "up 6\n" +
                "down 8\n" +
                "forward 4\n" +
                "down 8\n" +
                "down 6\n" +
                "forward 2\n" +
                "forward 8\n" +
                "up 8\n" +
                "up 1\n" +
                "forward 6\n" +
                "down 2\n" +
                "down 6\n" +
                "forward 2\n" +
                "forward 2\n" +
                "down 8\n" +
                "forward 7\n" +
                "up 1\n" +
                "forward 1\n" +
                "down 8\n" +
                "forward 3\n" +
                "down 6\n" +
                "forward 7\n" +
                "forward 7\n" +
                "up 7\n" +
                "down 1\n" +
                "forward 8\n" +
                "up 7\n" +
                "forward 8\n" +
                "forward 8\n" +
                "forward 2\n" +
                "down 5\n" +
                "up 7\n" +
                "forward 1\n" +
                "forward 9\n" +
                "down 9\n" +
                "forward 8\n" +
                "down 6\n" +
                "down 7\n" +
                "up 4\n" +
                "down 5\n" +
                "forward 6\n" +
                "down 8\n" +
                "forward 5\n" +
                "up 6\n" +
                "up 4\n" +
                "forward 8\n" +
                "forward 5\n" +
                "forward 1\n" +
                "forward 3\n" +
                "up 2\n" +
                "down 3\n" +
                "down 4\n" +
                "down 2\n" +
                "forward 3\n" +
                "forward 2\n" +
                "up 8\n" +
                "up 1\n" +
                "forward 5\n" +
                "up 8\n" +
                "down 1\n" +
                "up 4\n" +
                "down 6\n" +
                "forward 1\n" +
                "down 3\n" +
                "up 8\n" +
                "down 3\n" +
                "forward 5\n" +
                "down 7\n" +
                "forward 3\n" +
                "down 1\n" +
                "up 8\n" +
                "up 6\n" +
                "down 4\n" +
                "down 8\n" +
                "up 2\n" +
                "forward 1\n" +
                "forward 8\n" +
                "down 4\n" +
                "down 8\n" +
                "down 4\n" +
                "up 7\n" +
                "down 4\n" +
                "forward 7\n" +
                "forward 4\n" +
                "forward 2\n" +
                "forward 6\n" +
                "up 4\n" +
                "down 5\n" +
                "forward 8\n" +
                "forward 9\n" +
                "down 1\n" +
                "down 2\n" +
                "down 2\n" +
                "forward 6\n" +
                "forward 1\n" +
                "forward 4\n" +
                "down 7\n" +
                "forward 6\n" +
                "forward 9\n" +
                "down 5\n" +
                "forward 9\n" +
                "up 4\n" +
                "down 2\n" +
                "down 6\n" +
                "forward 5\n" +
                "forward 3\n" +
                "forward 1\n" +
                "forward 6\n" +
                "forward 5\n" +
                "forward 2\n" +
                "down 9\n" +
                "forward 1\n" +
                "up 5\n" +
                "down 2\n" +
                "down 8\n" +
                "up 5\n" +
                "down 3\n" +
                "up 1\n" +
                "forward 5\n" +
                "forward 8\n" +
                "forward 2\n" +
                "down 3\n" +
                "down 7\n" +
                "up 3\n" +
                "up 8\n" +
                "forward 5\n" +
                "up 8\n" +
                "forward 4\n" +
                "down 7\n" +
                "forward 4\n" +
                "down 1\n" +
                "forward 2\n" +
                "forward 8\n" +
                "up 9\n" +
                "up 1\n" +
                "forward 3\n" +
                "down 6\n" +
                "up 5\n" +
                "down 9\n" +
                "forward 8\n" +
                "forward 3\n" +
                "down 7\n" +
                "forward 3\n" +
                "up 9\n" +
                "down 2\n" +
                "forward 2\n" +
                "down 6\n" +
                "down 9\n" +
                "down 4\n" +
                "down 4\n" +
                "down 7\n" +
                "up 6\n" +
                "up 2\n" +
                "down 7\n" +
                "forward 5\n" +
                "up 1\n" +
                "down 6\n" +
                "up 2\n" +
                "forward 8\n" +
                "up 6\n" +
                "forward 4\n" +
                "down 2\n" +
                "up 5\n" +
                "down 6\n" +
                "down 5\n" +
                "forward 8\n" +
                "forward 4\n" +
                "down 5\n" +
                "forward 5\n" +
                "forward 3\n" +
                "down 2\n" +
                "forward 3\n" +
                "up 3\n" +
                "down 4\n" +
                "up 2\n" +
                "forward 9\n" +
                "up 8\n" +
                "forward 9\n" +
                "up 5\n" +
                "up 1\n" +
                "forward 9\n" +
                "down 8\n" +
                "down 3\n" +
                "forward 9\n" +
                "up 4\n" +
                "down 1\n" +
                "forward 8\n" +
                "down 6\n" +
                "down 1\n" +
                "down 2\n" +
                "down 9\n" +
                "down 1\n" +
                "forward 5\n" +
                "down 7\n" +
                "forward 1\n" +
                "up 6\n" +
                "down 1\n" +
                "down 6\n" +
                "forward 6\n" +
                "forward 9\n" +
                "down 6\n" +
                "forward 1\n" +
                "forward 4\n" +
                "up 4\n" +
                "forward 1\n" +
                "up 9\n" +
                "forward 3\n" +
                "forward 8\n" +
                "down 3\n" +
                "down 7\n" +
                "forward 4\n" +
                "up 1\n" +
                "down 1\n" +
                "forward 1\n" +
                "down 3\n" +
                "down 6\n" +
                "down 9\n" +
                "down 6\n" +
                "forward 4\n" +
                "down 1\n" +
                "up 4\n" +
                "forward 8\n" +
                "down 6\n" +
                "up 6\n" +
                "down 5\n" +
                "up 8\n" +
                "forward 4\n" +
                "up 7\n" +
                "forward 4\n" +
                "forward 2\n" +
                "down 7\n" +
                "forward 2";
    }
}
